Models/DueDate.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace HelpRon.Models
{
    public class DueDate
    {
        public int ID { get; set; }
        public string Title { get; set; }

        [Display(Name = "Due Date")]
        [DataType(DataType.Date)]
        public DateTime dueDate { get; set; }
        public string Helper { get; set; }
    
    }
}

Models/ErrorViewModel.cs
using System;

namespace HelpRon.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Need.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace HelpRon.Models
{
    public class Need
    {
        public int Id { get; set; }
        public string Name { get; set; }

        [DataType(DataType.Date)]
        public DateTime DueDate { get; set; }
        public string Helper { get; set; }
   
    }
}

Models/NeedHelperViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;

namespace HelpRon.Models
{
    public class NeedHelperViewModel
    {
        
        
        public List<Need> Needs { get; set; }
        public SelectList Helper { get; set; }
        public string NeedHelper { get; set; }
        public string SearchString { get; set; }
    }
      
}

Models/SeedData.cs
using HelpRon.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using System;
using System.Linq;

namespace HelpRon.Models
{
    public static class SeedData
    {
        public static void Initialize(IServiceProvider serviceProvider)
        {
            using (var context = new HelpRonContext(
                serviceProvider.GetRequiredService<
                    DbContextOptions<HelpRonContext>>()))
            {
                // Look for any needs.
                if (context.Need.Any())
                {
                    return;   // DB has been seeded
                }

                context.Need.AddRange(
                    new Need
                    {
                        Name = "Buy more Oak",
                        DueDate = DateTime.Parse("2022-5-12"),
                        Helper = "Ann",
                       
                    },

                    new Need
                    {
                        Name = "Get Eggs",
                        DueDate = DateTime.Parse("2022-8-2"),
                        Helper = "Leslie",

                    },

                     new Need
                     {
                         Name = "Buy a cow",
                         DueDate = DateTime.Parse("2022-2-12"),
                         Helper = "April",

                     },

                   new Need
                   {
                       Name = "Buy a shovel",
                       DueDate = DateTime.Parse("2021-6-19"),
                       Helper = "Andy",
                   }


               );
                context.SaveChanges();
            }
        }
    }
}

Controllers/HelloWorldController.cs
using Microsoft.AspNetCore.Mvc;
using System.Text.Encodings.Web;

namespace HelpRon.Controllers
{
    public class HelloWorldController : Controller
    {
      

        public IActionResult Welcome(string name, int numTimes = 1)
        {
            ViewData["Message"] = "Hello " + name;
            ViewData["NumTimes"] = numTimes;

            return View();
        }
    }
}

Controllers/HomeController.cs

using Microsoft.AspNetCore.Mvc;
using System.Text.Encodings.Web;

namespace HelpRon.Controllers
{

    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Controllers/NeedsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using HelpRon.Models;
using System;
using System.Linq;
using System.Threading.Tasks;
using HelpRon.Data;

namespace Needs.Controllers

{
    public class NeedsController : Controller
    {
        private readonly HelpRonContext _context;

        public NeedsController(HelpRonContext context)
        {
            _context = context;
        }

        #region snippet_details
        // GET: Needs/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var need = await _context.Need
                .SingleOrDefaultAsync(m => m.Id == id);
            if (need == null)
            {
                return NotFound();
            }

            return View(need);
        }
        #endregion
        #region snippetCreate
        // GET: Needs/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Needs/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(
            [Bind("ID,Name,DueDate,Helper")] Need need)
        {
            if (ModelState.IsValid)
            {
                _context.Add(need);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(need);
        }
        #endregion

        // GET: Needs/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var need = await _context.Need.SingleOrDefaultAsync(m => m.Id == id);
            if (need == null)
            {
                return NotFound();
            }
            return View(need);
        }

        // POST: Needs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Name,DueDate,Helper")] Need need)
        {
            if (id != need.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(need);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!NeedExists(need.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }
            return View(need);
        }

        #region snippet_delete
        #region snippet_delete2
        // GET: Needs/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            #endregion
            if (id == null)
            {
                return NotFound();
            }

            var movie = await _context.Need
                .SingleOrDefaultAsync(m => m.Id == id);
            if (movie == null)
            {
                return NotFound();
            }

            return View(movie);
        }

        #region snippet_delete3
        // POST: Movies/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            #endregion
            var need = await _context.Need.SingleOrDefaultAsync(m => m.Id == id);
            _context.Need.Remove(need);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }
        #endregion

        private bool NeedExists(int id)
        {
            return _context.Need.Any(e => e.Id == id);
        }
    }
}

Views/HelloWorld/Index.cshtml
@{
    ViewData["Title"] = "Let's Help Ron";
}

<h2>Needs List</h2>

<p>Hello!</p>

Views/HelloWorld/Index2.cshtml
@{
    ViewData["Title"] = "Needs List";
}

<h2>Ron's Needs List</h2>

<p>Hello from our View Template!</p>

Views/HelloWorld/Welcome.cshtml
\@{
    ViewData["Title"] = "Welcome";
}

< h2 > Welcome </ h2 >

< ul >
    @for(int i = 0; i < (int)ViewData["NumTimes"]; i++)
    {
        < li > @ViewData["Message"] </ li >
    }
</ ul >

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Needs/Create.cshtml
@model HelpRon.Models.Need

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Need</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DueDate" class="control-label"></label>
                <input asp-for="DueDate" class="form-control" />
                <span asp-validation-for="DueDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Helper" class="control-label"></label>
                <input asp-for="Helper" class="form-control" />
                <span asp-validation-for="Helper" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Needs/Delete.cshtml
@model HelpRon.Models.Need

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Need</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DueDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DueDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Helper)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Helper)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Needs/Details.cshtml
@model HelpRon.Models.Need

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Need</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DueDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DueDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Helper)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Helper)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Needs/Edit.cshtml
@model HelpRon.Models.Need

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Need</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DueDate" class="control-label"></label>
                <input asp-for="DueDate" class="form-control" />
                <span asp-validation-for="DueDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Helper" class="control-label"></label>
                <input asp-for="Helper" class="form-control" />
                <span asp-validation-for="Helper" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Needs/Index.cshtml

@model HelpRon.Models.NeedHelperViewModel


@{ ViewData["Title"] = "Index"; }

<h2>Index</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>

<h2>Index</h2>


<form asp-controller="Needs" asp-action="Index" method="get">
    <p>
        <select asp-for="NeedHelper" asp-items="Model.Helper">
            <option value="">All</option>
        </select>

        Title: <input type="text" name="SearchString" />
        <input type="submit" value="Filter" />
    </p>
</form>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Needs[0].Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Needs[0].DueDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Needs[0].Helper)
            </th>
            <th>

            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Needs)
        {
<tr>
    <td>
        @Html.DisplayFor(modelItem => item.Name)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.DueDate)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Helper)
    </td>

    <td>
        <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
        <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
        <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
    </td>
</tr>}
    </tbody>
</table> 

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Help Ron</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-controller="Needs" asp-action="Index">Help Ron</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Help Ron - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>